config/routes.rb
Physicsims::Application.routes.draw do

  
  root 'pages#index'
  get 'simulations' => 'pages#simulations'
  get 'simulations/:id' => 'pages#gallery', as: :gallery
  get 'videos' => 'pages#videos'
  get 'pictures' => 'pages#pictures'

end

app/models/pic.rb
class Pic < ActiveRecord::Base
end

app/models/sim.rb
class Sim < ActiveRecord::Base
end

app/models/vid.rb
class Vid < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end

	def simulations
		@simulations = Sim.all
	end

	def gallery
		@sim = Sim.find(params[:id])
	end

	def videos
		@videos = Vid.all
	end

	def pictures
		@pictures = Pic.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Physicsims</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
	<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">PhysicSims</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li>
					<a href="/">Home</a>
				</li>
				<li>
					<a href="/simulations">Sims</a>
				</li>
				<li>
					<a href="/videos">Vids</a>
				</li>
				<li>
					<a href="/pictures">Pics</a>
				</li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</div>

<%= yield %>

</body>
</html>

app/views/pages/gallery.html.erb
<% content_for :head do %>
	<script type="text/processing" data-processing-target="processing-canvas" src = "<%= @sim.link %>">
</script>
<%end%>

<div class="container">
<h1><%= @sim.name %></h1>
</div>

<center>
<canvas id="processing-canvas" style = "background: grey; border: solid black 2px;"></canvas>

<p style="width: 800px"><%= @sim.description %></p><br>

</center>

app/views/pages/index.html.erb
      

<div class="jumbotron" style="color: black; background-image: url(/assets/background.png);">     <div class="container">
	<center>
		<h1><br>PhysicSims</h1>       
		<p style="width: 800px">
			<br>PhysicSims is a peer to peer educational portal. It is a collection of physics education resources made by students for students.
		</p>
		<p></p>
	</center>
	</div>
</div>

<div class="container">     <!-- Example row of columns -->     
	<div class="row">
		<div class="col-md-4">
			<h2>Simulations</h2>
			<p>Browse our list of simulations. Topics covered include light polarization, electrons through parallel plates and cyclotrons. All simulations are in-browser and require no downloads.</p>
			<p><a class="btn btn-default" href="/simulations" role="button">View details »</a></p>
		</div>

		<div class="col-md-4">
			<h2>Videos</h2>
			<p>Check out Jake's videos. Topics covered include quantum physics, gravity and electricity and geostationary satellites. Be sure to check out the Youtube channel for more.</p>
			<p><a class="btn btn-default" href="/videos" role="button">View details »</a></p>
		</div>

		<div class="col-md-4">
			<h2>Pictures</h2>
			<p>Take a look at Mackenzie's Pictures. Topics covered include gravity, light diffraction and electric and magnetic fields. Full sized images are included as links on seperate pages.</p>
			<p><a class="btn btn-default" href="/pictures" role="button">View details »</a></p>
		</div>
	</div>
	<hr>
	<footer><p>By Rees and Isaac</p></footer>   
</div> <!-- /container -->

</html>

app/views/pages/simulations.html.erb
<% @simulations.each do |s| %>

<div class="jumbotron" style="color: black;">     <div class="container">
<h1><%= s.name %></h1>
<%= image_tag s.image %>
<p><%= s.description %></p>

<a class="btn btn-default" href="<%= gallery_path(s) %>" role="button">Check it out</a>
<br>

</div>
</div>

<%end%>